### ISSUE TITLE
Signals.SIGSEGV in OSX tests in ESMPy that seem likely to be from ESMF

### ISSUE THREAD

**Issue by xylar** [conda-forge/esmf-feedstock#81]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We're seeing a bunch of seg faults in OSX testing in https://github.com/conda-forge/esmpy-feedstock/pull/58.  I think they must come from #

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by xylar** [comment]
An example:
```
test_grid_create_from_file_scrip_decomp_balanced_cyclic (ESMF.test.test_api.test_grid.TestGrid) ... Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    setup(name="ESMPy",
  File "/Users/runner/miniforge3/conda-bld/esmpy_1667300230078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/runner/miniforge3/conda-bld/esmpy_1667300230078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/runner/miniforge3/conda-bld/esmpy_1667300230078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    subprocess.check_call(cmd)
  File "/Users/runner/miniforge3/conda-bld/esmpy_1667300230078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nosetests', '-vs', '--with-xunit', '-a', '!slow,!parallel', 'src/ESMF']' died with <Signals.SIGSEGV: 11>.
```

**Comment by xylar** [comment]
Closing because we now have a working ESMPy build as far as we can tell.
